# docker-compose.yml

services:
  studentmanager-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: bubhux/repository-student-manager:latest
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    command: ""
    depends_on:
      - mongo
    environment:
      - DOCKER=true
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    env_file:
      - .env
    networks:
      - student_network

  mongo:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    image: bubhux/repository-student-manager:mongo-3.6
    container_name: mongodb
    environment:
      - MONGO_INITDB_STORAGE_ENGINE=wiredTiger
    ports:
      - "27017:27017"
    networks:
      - student_network
    volumes:
      - mongodb_data:/data/db
    restart: no
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongodb_data:

networks:
  student_network:
    driver: bridge
